packages:
  - "apps/*"
  - "packages/*"

syncInjectedDepsAfterScripts:
  - build

injectWorkspacePackages: true

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  lefthook: true
  prisma: true
